version: 0.1

phases:
  install:
    commands:
      - echo Install started on `date`
  pre_build:
    commands:
      - echo Pre Build started on `date`
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew --debug --stacktrace build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app/build/outputs/apk/app-release-unsigned.apk
    - app/build/outputs/apk/app-debug.apk
  discard-paths: yes
